name: "Continuous Integration Checks"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  depcheck:
    runs-on: ubuntu-latest
    name: "Check dependencies"
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "yarn"
        env:
          NODE_ENV: development
      - run: yarn install
      - run: yarn depcheck

  lint:
    runs-on: ubuntu-latest
    name: "Lint code"
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "yarn"
        env:
          NODE_ENV: development
      - run: yarn install
      - run: yarn lint

  types:
    runs-on: ubuntu-latest
    name: "Check types"
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "yarn"
        env:
          NODE_ENV: development
      - run: yarn install
      - run: yarn types
